"""empty message

Revision ID: 563273ab2de9
Revises: 9ec9316f5ead
Create Date: 2021-01-24 19:52:19.721031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563273ab2de9'
down_revision = '9ec9316f5ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
